/* ******************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
**        author  zhuwei1   QQ: 277251257                        **
** 		                                						  **
** *****************************************************************/

//   
 // User Define Macros.   

using System.IO;
using System;

namespace GEM_NET_LIB
{
    public class CSocketInfo
    {
        public string m_ServerIP;
        public int m_Port;
        //public uint m_Uin = 0;

    }
}
