//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.2008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;

namespace NetClient
{
	public class LogFile    
	{        
		private static string logPath = string.Empty;//日志存储路径
		private static StreamWriter logWriter;

		public static string LogPath
		{    
			get
			{
				return logPath;			       
			}
			set 
			{
				logPath = value;
				logWriter = new StreamWriter(logPath);
			}
		}

		
		private static string logFielPrefix = string.Empty; 
		public static  string LogFielPrefix 
		{			
			get
			{ 
				return logFielPrefix; 
			} 
			set
			{ logFielPrefix = value; } 
		} 
		

				
		public static void WriteLog(string logEvel, string msg) 
		{ 
			
			try
			{  
				logWriter = File.CreateText(LogFielPrefix + logEvel +  " " +  DateTime.Now.ToString("yyyyMMdd") + ".Log");
				System.IO.StreamWriter sw = System.IO.File.AppendText( LogPath + LogFielPrefix + logEvel +  " "
				          +  DateTime.Now.ToString("yyyyMMdd") + ".Log");  
				sw.WriteLine(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss: ") + msg);  
				sw.Close(); 
			}			
			catch				
			{ } 
		}

		public static void WriteLog(LOGEvel logEvel, string msg) 
		{  
			WriteLog(logEvel.ToString(), msg); 
		}

		public enum LOGEvel 
		{  
			DEBUG,
			Trace, 
			Warning, 
			Error
		}
	}
}

