//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.2008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using UdpKit;
using System.Text;

namespace GEM_NET_LIB
{
	//int and bytes, to change to be header
	public class  P2PSerializer : UdpSerializer {
		public override bool Pack (UdpStream stream, ref object o) {
			// cast to string and get bytes
			byte[] bytes = (byte[])(o);
			
			// write length and bytes into buffer
			stream.WriteInt(bytes.Length);
			stream.WriteByteArray(bytes);
			
			return true;
		}
		
		public override bool Unpack (UdpStream stream, ref object o) {
			// read length and create array, then read bytes into array
			byte[] bytes = new byte[stream.ReadInt()];
			stream.ReadByteArray(bytes);
			
			// convert bytes to string
			o = bytes;
			return true;
		}
	}
}
